[tool.poetry]
name = "dangerzone"
version = "0.3.1"
description = "Take potentially dangerous PDFs, office documents, or images and convert them to safe PDFs"
authors = ["Micah Lee <micah.lee@theintercept.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
click = "*"
appdirs = "*"
requests = "*"
macholib = "*"
termcolor = "*"
PySide6 = "6.2.*" # 6.2 is LTS
colorama = "*"
psutil = "*"
cx_freeze = {version = "*", platform = "win32"}
pywin32 = {version = "*", platform = "win32"}
wmi = {version = "*", platform = "win32"}
pyxdg = {version = "*", platform = "linux"}
pyinstaller = {version = "*", platform = "darwin"}
strip-ansi = {version = "*", platform = "darwin"}

[tool.poetry.dev-dependencies]
setuptools = {version = "*", platform = "win32"}
black = "*"
typing-extensions = "*"
types-Pillow = "*"
types-appdirs = "*"
pyxdg = "*"

[tool.poetry.scripts]
dangerzone = 'dangerzone:main'
dangerzone-container = 'dangerzone:main'
dangerzone-cli = 'dangerzone:main'

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
